# Generated by Django 3.0.3 on 2020-02-20 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newitem',
            old_name='new_item',
            new_name='new',
        ),
    ]
